document.writeln("<nav class=\'navbar navbar-default\' role=\'navigation\'>");
document.writeln("    <div class=\'container-fluid\'>");
document.writeln("        <div class=\'navbar-header\'>");
document.writeln("            <a class=\'navbar-brand\' href=\'./bio-index.html\'>我在B站学生物</a>");
document.writeln("        </div>");
document.writeln("        <ul class=\'nav navbar-nav\'>");
document.writeln("            <li class=\'dropdown\'>");
document.writeln("                <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("                    必修一：分子与细胞");
document.writeln("                    <b class=\'caret\'></b>");
document.writeln("                </a>");
document.writeln("                <ul class=\'dropdown-menu\'>");
document.writeln("                    <li><a href=\'./bio-01-index.html\'>第1章  绪论——生物界与生物学</a></li>");
document.writeln("                    <li><a href=\'./bio-02-index.html\'>第2章  生物的化学组成</a></li>");
document.writeln("                    <li><a href=\'./bio-03-index.html\'>第3章  细胞的结构</a></li>");
document.writeln("                    <li><a href=\'./bio-04-index.html\'>第4章  物质的跨膜运输</a></li>");
document.writeln("                    <li><a href=\'./bio-05-index.html\'>第5章  细胞代谢</a></li>");
document.writeln("                    <li><a href=\'./bio-06-index.html\'>第6章  细胞的生命历程</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li class=\'dropdown\'>");
document.writeln("                <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("                    必修二：遗传与进化");
document.writeln("                    <b class=\'caret\'></b>");
document.writeln("                </a>");
document.writeln("                <ul class=\'dropdown-menu\'>");
document.writeln("                    <li><a href=\'./bio-07-index.html\'>第7章  遗传的细胞基础</a></li>");
document.writeln("                    <li><a href=\'./bio-08-index.html\'>第8章  遗传的分子基础</a></li>");
document.writeln("                    <li><a href=\'./bio-09-index.html\'>第9章  遗传的基本规律</a></li>");
document.writeln("                    <li><a href=\'./bio-10-index.html\'>第10章 变异与进化</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li class=\'dropdown\'>");
document.writeln("                <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("                    选择性必修一：稳态与调节");
document.writeln("                    <b class=\'caret\'></b>");
document.writeln("                </a>");
document.writeln("                <ul class=\'dropdown-menu\'>");
document.writeln("                    <li><a href=\'./bio-11-index.html\'>第11章 内环境与稳态</a></li>");
document.writeln("                    <li><a href=\'./bio-12-index.html\'>第12章 神经调节</a></li>");
document.writeln("                    <li><a href=\'./bio-13-index.html\'>第13章 体液调节</a></li>");
document.writeln("                    <li><a href=\'./bio-14-index.html\'>第14章 免疫调节</a></li>");
document.writeln("                    <li><a href=\'./bio-15-index.html\'>第15章 植物生理</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li class=\'dropdown\'>");
document.writeln("                <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("                    选择性必修二：生态与环境");
document.writeln("                    <b class=\'caret\'></b>");
document.writeln("                </a>");
document.writeln("                <ul class=\'dropdown-menu\'>");
document.writeln("                    <li><a href=\'./bio-16-index.html\'>第16章 种群与群落</a></li>");
document.writeln("                    <li><a href=\'./bio-17-index.html\'>第17章 生态系统</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li class=\'dropdown\'>");
document.writeln("                <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("                    选择性必修三：生物技术与工程");
document.writeln("                    <b class=\'caret\'></b>");
document.writeln("                </a>");
document.writeln("                <ul class=\'dropdown-menu\'>");
document.writeln("                    <li><a href=\'#\' disabled=\'disabled\'>第18章 发酵工程</a></li>");
document.writeln("                    <li><a href=\'#\' disabled=\'disabled\'>第19章 细胞工程</a></li>");
document.writeln("                    <li><a href=\'#\' disabled=\'disabled\'>第20章 基因工程</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</nav>");